### PR TITLE
Bump qpid-proton version to 0.18.1

### PR DESCRIPTION
**Pull request by gasper-vrhovsek**
Bump qpid-proton version to 0.18.1

Addresses https://github.com/ManageIQ/manageiq-providers-nuage/issues/42

@miq-bot add_label enhancement
/cc @gberginc 
/cc @miha-plesko

### CODE REVIEW

**Comment by gasper-vrhovsek** [comment]
@miq-bot assign @gberginc

**Comment by gberginc** [comment]
@miq-bot add_label gaprindashvili/yes

**Comment by gberginc** [comment]
@gasper-vrhovsek please add the PR to the core that uses 0.18.1 qpid-proton from rubygems.

**Comment by gberginc** [comment]
@bronaghs This patch is required because we are trying to replace the qpid-proton gem hosted on our GitHub with the one published on Rubygems. This wasn't possible before qpid-proton 0.18.1 because of a dependency that caused an issue with ManageIQ. We have tested with 0.18.1 gem and it works.

It's basically just a build command for Travis, but mandatory for Gem version update.

**Comment by gberginc** [comment]
@miq-bot assign @bronaghs

**Comment by gasper-vrhovsek** [comment]
@gberginc PR added: https://github.com/ManageIQ/manageiq/pull/16498

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit f10303fe6a847fdf45b982ee3532c2222ff02f13
Author: Bronagh Sorota <bsorota@redhat.com>
Date:   Tue Nov 21 08:59:31 2017 -0500

    Merge pull request #44 from gasper-vrhovsek/feature/bump_qpid_0.18.1
    
    Bump qpid-proton version to 0.18.1
    (cherry picked from commit a1f64a1cc408240e3f739a317c6e0b96dab90668)
```

**Pull request merged**
