### PR TITLE
Remove swig from travis

### PR DESCRIPTION
**Pull request by gasper-vrhovsek**
This will remove swig from qpid_install.sh.

### CODE REVIEW

**Comment by gasper-vrhovsek** [comment]
@gberginc Travis checks were completed successfully, would you like to take another look at the changes before we submit this for review?

**Comment by gberginc** [comment]
@gasper-vrhovsek remove the `require 'qpid_proton` (it's just used to ensure that qpid is available) from this PR and we are GTG.

**Comment by gasper-vrhovsek** [comment]
@Fryguy this PR addresses your [comment](https://github.com/ManageIQ/manageiq-providers-nuage/pull/25#issuecomment-339014362) about removal of swig.

@miq-bot assign @Fryguy
@miq-bot remove_label wip

/cc @gberginc

**Comment by gberginc** [comment]
Thanks @gasper-vrhovsek!

LGTM

**Pull request merged**
