### PR TITLE
[GAPRINDASHVILI] [CHANGELOG] Update for Gaprindashvili-1

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot remove_label wip

**Comment by juliancheal** [comment]
@JPrause is this ready to be merged? Or are you still updating it?

**Comment by JPrause** [comment]
@juliancheal yessir. 👍

**Comment by JPrause** [comment]
ready

**Pull request merged**
