### PR TITLE
Bug 1518304: Don't show events tab for openstack network provider edit

### PR DESCRIPTION
**Pull request by sseago**
Add supports entry for events configuration for nuage network provider.

After https://github.com/ManageIQ/manageiq-ui-classic/pull/3832 this is needed to show the event tab for the cloud and infra provider edit page.

### CODE REVIEW

**Comment by gberginc** [comment]
@miha-plesko please test Nuage with this patch.

**Comment by sseago** [comment]
@gberginc @miha-plesko It will need to wait for the related manageiq and manageiq-ui-classic PRs before testing this one. From the discussion on https://github.com/ManageIQ/manageiq/pull/17479 I expect this PR will be revised before the other PRs get merged.

**Comment by miha-plesko** [comment]
I didn't realize OpenStack supports editing network manager - is this something new? Because generally we hide the whole edit form for all other providers but nuage.

**Comment by sseago** [comment]
@miha-plesko For OpenStack, the edit action is available. I'm not sure whether this is new, though ( @mansam -- do you know?) However, the 'events' content is not available for the OpenStack edit form. The change here is to make sure that the events endpoint tab still shows up for nuage when we hide that for OpenStack. See the discussion on https://github.com/ManageIQ/manageiq/pull/17479 though, as the outcome of that will probably change what gets done in this PR.

**Comment by miha-plesko** [comment]
@sseago I've posted a [detailed comment](https://github.com/ManageIQ/manageiq-ui-classic/pull/3832#issuecomment-392308603) on the original PR but I'm pretty sure that Edit page shouldn't be displayed at all for OpenStack network manager. That being said I still don't mind to test this PR in case the UI and core PRs get merged 👍

**Comment by sseago** [comment]
@miha-plesko as discussed on the other PR, I'm closing this PR, since the original bug fix no longer needs to make provider-level changes.

**Pull request closed without merging**
