### PR TITLE
Update DDF schema to version 2

### PR DESCRIPTION
**Pull request by skateman**
https://github.com/ManageIQ/manageiq-ui-classic/issues/7277

### CODE REVIEW

**Comment by himdel** [comment]
the js schema is still using `validatorTypes.PATTERN_VALIDATOR`, it's just `validatorTypes.PATTERN` now

**Comment by skateman** [comment]
@agrare can you please verify that the CI failure is unrelated?

**Comment by agrare** [comment]
Looks like the VCRs are failing after updating rest-client, I'll look at this today

**Review by himdel — APPROVED** [review]

**Comment by skateman** [comment]
@miq-bot assign @Fryguy

**Comment by agrare** [comment]
Specs should be fixed by https://github.com/ManageIQ/manageiq-providers-nuage/pull/222

**Pull request merged**
