### PR TITLE
Fix exception handing for credential validation on raw_connect

### PR DESCRIPTION
**Pull request by tumido**
When provider is added the credentials validation is newly done via `raw_connect` (class method) instead of `verify_credentials` (needed EMS object). Further reading on this change can be found here: ManageIQ/manageiq-ui-classic#1580

This change ensures that exceptions are handled properly, because the `verify_credentials` is not called anymore.

Similar PRs for other providers:
- https://github.com/ManageIQ/manageiq-providers-azure/pull/161
- https://github.com/ManageIQ/manageiq-providers-hawkular/pull/100
- https://github.com/ManageIQ/manageiq-providers-scvmm/pull/41
- https://github.com/ManageIQ/manageiq-providers-google/pull/28
- https://github.com/ManageIQ/manageiq-providers-lenovo/pull/108

### CODE REVIEW

**Comment by tumido** [comment]
cc @jntullo

**Comment by bronaghs** [comment]
@gberginc - can you review.

**Comment by gberginc** [comment]
Code LGTM

@gasper.vrhovsek please check

@miq-bot add_label bug, gaprindashvili/yes

**Comment by gasper-vrhovsek** [comment]
@gberginc LGTM

**Comment by gberginc** [comment]
Thanks @gasper-vrhovsek (and sorry for mistyping your username, causing the delay).

@bronaghs @juliancheal this looks good now and is ready to be merged

@miq-bot assign @juliancheal

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 810dfb18dd361bb9ca88f77738aed7e3d5575b24
Author: Bronagh Sorota <bsorota@redhat.com>
Date:   Tue Nov 21 08:53:30 2017 -0500

    Merge pull request #40 from tumido/fix_cred_validation
    
    Fix exception handing for credential validation on raw_connect
    (cherry picked from commit 8fe2ff3832896badfe556e916f92d706b1cc1204)
```

**Pull request merged**
