### PR TITLE
[IVANCHUK] Change travis.yml to use the only supported ruby, 2.5.3

### PR DESCRIPTION
**Pull request by d-m-u**
Change travis.yml to use the only supported ruby, 2.5.3

### CODE REVIEW

**Comment by simaishi** [comment]
Just like manageiq-ui-classic... this will cause `yarn:test` to not run at all... can we remove `matrix` section?

FYI, ui-classic is modifying a test to make sure we run test for 1 ruby version: https://github.com/ManageIQ/manageiq-ui-classic/pull/5885

**Comment by simaishi** [comment]
^ cc @miha-plesko

**Comment by miha-plesko** [comment]
Thanks for ping, lemme fix this on Monday

**Comment by miha-plesko** [comment]
@simaishi TBH I don't see how `excludes` block could cause Travis from skipping javascript tests - I think in worst case it'd cause redundant re-runs of it (when there is no match). However, I've introduced rspec to be sure, thanks for pointing out:

- https://github.com/ManageIQ/manageiq-providers-nuage/pull/182 (rspec only)
- https://github.com/ManageIQ/manageiq-providers-nuage/pull/183 (updated travis + rspec)

**Pull request merged**
