### PR TITLE
[WIP] Update changelog for Fine-4

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by juliancheal** [comment]
LGTM, if you're done @JPrause we can remove the wip and I'll merge.

**Comment by JPrause** [comment]
@juliancheal I need to close this one, I rushed this and need to review from a clean start.

**Comment by juliancheal** [comment]
@JPrause No worries :)

**Pull request closed without merging**
